### ISSUE TITLE
createNewEntries error ?

### ISSUE THREAD

**Issue by noman798** [Kapps/ShardTools#1]
https://github.com/Kapps/ShardTools/commit/c3d3e50ec2ccb0a1a0defadf385c6dd3b4f2128c#diff-604843f2aad0849966d4a59ac5a05663

**Comment by Kapps** [comment]
Sorry, I should have marked that class as disabled. I started on it at some point, but never got to the point of an even partially working implementation. I ended up not needing it, so I don't think it will get finished any time soon.
